window.MOVIES = [
  { id: 1, title: "Horizonte Zero", type: "Filme", year: 2026, duration: "2h 14min", age: "16+", genre: "Aventura · Drama", description: "Depois de uma grande descoberta, uma família precisa atravessar uma cidade desconhecida para chegar ao único lugar seguro que restou.", c1: "#7d1d2e", c2: "#10151d", progress: 64 },
  { id: 2, title: "Código de Família", type: "Filme", year: 2025, duration: "1h 52min", age: "12+", genre: "Ação · Suspense", description: "Um código escondido dentro de um álbum antigo coloca irmãos em lados diferentes de uma mesma investigação.", c1: "#174d61", c2: "#0d1017", progress: 32 },
  { id: 3, title: "O Último Verão", type: "Filme", year: 2024, duration: "1h 48min", age: "12+", genre: "Drama · Romance", description: "Quatro amigos retornam ao lugar onde cresceram e descobrem que certas histórias ainda não terminaram.", c1: "#a85c28", c2: "#241214", progress: 0 },
  { id: 4, title: "Planeta Vermelho", type: "Filme", year: 2023, duration: "2h 03min", age: "10+", genre: "Ficção · Aventura", description: "Uma missão de pesquisa encontra sinais de vida e precisa decidir entre voltar para casa ou continuar explorando.", c1: "#9d2c18", c2: "#1a0d0b", progress: 0 },
  { id: 5, title: "Noite Sem Fim", type: "Filme", year: 2025, duration: "1h 59min", age: "16+", genre: "Suspense", description: "Um grupo de amigos fica preso em uma estrada isolada e percebe que está sendo observado.", c1: "#26385d", c2: "#080b13", progress: 0 },
  { id: 6, title: "Entre Nós", type: "Filme", year: 2022, duration: "1h 42min", age: "12+", genre: "Drama", description: "Duas gerações de uma família tentam reconstruir a relação após anos sem conversar sobre o passado.", c1: "#786024", c2: "#16110a", progress: 0 },
  { id: 7, title: "Distrito 27", type: "Filme", year: 2026, duration: "2h 21min", age: "16+", genre: "Ação · Crime", description: "Uma investigação leva uma detetive até a parte da cidade onde ninguém quer fazer perguntas.", c1: "#315777", c2: "#0c1015", progress: 0 },
  { id: 8, title: "A Última Chamada", type: "Filme", year: 2024, duration: "1h 37min", age: "14+", genre: "Mistério", description: "Um telefonema aparentemente comum revela uma história que estava enterrada há décadas.", c1: "#4e245b", c2: "#110b16", progress: 0 },
  { id: 9, title: "Casa 8", type: "Filme", year: 2026, duration: "1h 49min", age: "12+", genre: "Terror · Mistério", description: "Uma nova família se muda para uma casa onde cada morador anterior deixou uma regra diferente.", c1: "#2f4c3b", c2: "#080d0a", progress: 0 },
  { id: 10, title: "Recomeço", type: "Filme", year: 2023, duration: "1h 43min", age: "10+", genre: "Drama", description: "Depois de uma mudança inesperada, uma jovem encontra novos amigos e uma nova razão para ficar.", c1: "#6c4141", c2: "#18100f", progress: 0 },
  { id: 11, title: "Linha de Frente", type: "Série", year: 2026, duration: "2 temporadas", age: "16+", genre: "Ação · Crime", description: "Uma equipe especial tenta impedir uma sequência de crimes que conecta diferentes pontos da cidade.", c1: "#344b63", c2: "#0b1017", progress: 41 },
  { id: 12, title: "Os de Casa", type: "Série", year: 2025, duration: "1 temporada", age: "12+", genre: "Comédia · Família", description: "Na casa mais movimentada do bairro, cada jantar vira uma história nova.", c1: "#ac702e", c2: "#25160a", progress: 18 },
  { id: 13, title: "Depois da Chuva", type: "Série", year: 2024, duration: "3 temporadas", age: "14+", genre: "Drama", description: "Uma cidade pequena tenta se recuperar enquanto antigos segredos voltam à superfície.", c1: "#3e6472", c2: "#0b1116", progress: 0 },
  { id: 14, title: "Fora do Mapa", type: "Série", year: 2026, duration: "1 temporada", age: "14+", genre: "Aventura · Mistério", description: "Cinco amigos encontram um mapa que não deveria existir e resolvem seguir a primeira pista.", c1: "#5c6e24", c2: "#101409", progress: 0 },
  { id: 15, title: "Arquivo 1989", type: "Série", year: 2023, duration: "2 temporadas", age: "16+", genre: "Mistério · Suspense", description: "Documentos antigos revelam uma operação esquecida e colocam um jornalista em risco.", c1: "#6e3033", c2: "#12090b", progress: 0 },
  { id: 16, title: "Horizonte Norte", type: "Série", year: 2025, duration: "1 temporada", age: "12+", genre: "Drama · Aventura", description: "Uma família recomeça a vida em uma região distante e descobre uma comunidade cheia de histórias.", c1: "#1e5368", c2: "#091116", progress: 0 }
];
